<a href="https://colab.research.google.com/github/sabiandika/learn-code-in-google-collab/blob/main/WEEK_2%2C_DATA_SCIENCE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. NUMPY FOR NUMRICAL


In [11]:
import numpy as np

arr = np.array ([1,2,23])
print(arr,"\n")

zeros = np.zeros((2,3))
print(zeros,"\n")

ones = np.ones((2,3))
print(ones,"\n")

range_array = np.arange(1, 20, 3)
print(range_array,"\n")

linspace_arr = np.linspace(0, 9, 4)
print(linspace_arr,"\n")

random_arr = np.random.rand(2, 3)
print(random_arr,"\n")

[ 1  2 23] 

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[ 1  4  7 10 13 16 19] 

[0. 3. 6. 9.] 

[[0.31010934 0.3252433  0.84330058]
 [0.00697596 0.08953579 0.42770608]] 



In [12]:
import numpy as np

arr = np.array ([2,4,6,2,5,6])
reshaped = arr.reshape(3,2)
print(reshaped,"\n")

expanded = arr[:, np.newaxis]
print(expanded,"\n")

flattened = arr.flatten()
print(flattened,"\n")


[[2 4]
 [6 2]
 [5 6]] 

[[2]
 [4]
 [6]
 [2]
 [5]
 [6]] 

[2 4 6 2 5 6] 



MATH

In [13]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b,"\n")
print(a-b,"\n")
print(a*b,"\n")
print(a/b,"\n")

arr = np.array([4,16,25])
print(np.sqrt(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))


[5 7 9] 

[-3 -3 -3] 

[ 4 10 18] 

[0.25 0.4  0.5 ] 

[2. 4. 5.]
45
15.0
25


aray indexing slicing reshaping

In [14]:
import numpy as np

arr = np.array([1,2,3,4,5,6,56,42,23])
print(arr[2])
print(arr[-1])

print(arr[1:4])
print(arr[1:7:2])
print(arr[4:],"\n")

reshaped = arr.reshape(3,3)
print(reshaped,"\n")




3
23
[2 3 4]
[2 4 6]
[ 5  6 56 42 23] 

[[ 1  2  3]
 [ 4  5  6]
 [56 42 23]] 



In [15]:
import numpy as np
a = np.arange(1,6)
b = np.arange(6,11)

print(a)
print(b)

print("tambah",a+b)
print("kurang",a-b)
print("kali",a*b)
print("bagi",a/b)
print("pangkat",a**b)

print("\n")
print("\n")


[1 2 3 4 5]
[ 6  7  8  9 10]
tambah [ 7  9 11 13 15]
kurang [-5 -5 -5 -5 -5]
kali [ 6 14 24 36 50]
bagi [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
pangkat [      1     128    6561  262144 9765625]






In [16]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

#transpose
transpose = matrix.T
print("Transpose:\n", transpose)

another_matrix = np.array([[9,8,7],[6,5,4],[3,2,1]])
print("pertambahan:\n", matrix + another_matrix)
print("perkalian:\n", matrix * another_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
pertambahan:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
perkalian:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


DAY 2. NUMPY ADVANCED


Broadcasting di NumPy adalah fitur yang memungkinkan array dengan ukuran berbeda tetap bisa dilakukan operasi matematika tanpa harus menyamakan ukuran secara manual


Rules broadcasting di NumPy ada 3 aturan utama:

Dimensi dibandingkan dari kanan ke kiri
Shape array dicek mulai dari dimensi paling belakang.
Dua dimensi cocok jika:
ukurannya sama
contoh: (3,4) dengan (3,4)
atau salah satunya bernilai 1
contoh: (3,4) dengan (1,4)
Jika tidak sama dan tidak ada yang 1

In [17]:
import numpy as np

arr = np.array([1,2,3,5])
scalar = 2

result = arr + scalar
print(result)

matrix = np.array([[1,2,3],[4,5,6]])
scalar = 2
result = matrix + scalar
print("\n",result)

[3 4 5 7]

 [[3 4 5]
 [6 7 8]]


Aggregation di NumPy adalah proses menggabungkan banyak nilai menjadi satu nilai hasil.

Biasanya dipakai untuk:

jumlah (sum)
rata-rata (mean)
nilai terbesar (max)
nilai terkecil (min)

In [18]:

arr = np.array([[1,2,3], [4,5,6]])

print("sum",np.sum(arr))
print("mean",np.mean(arr))
print("max",np.max(arr))
print("min",np.min(arr))
print("Standar deviasi",np.std(arr))
print("Sum Baris:",np.sum(arr,axis=1))
print("Sum Kolom:",np.sum(arr,axis=0))



sum 21
mean 3.5
max 6
min 1
Standar deviasi 1.707825127659933
Sum Baris: [ 6 15]
Sum Kolom: [5 7 9]


Boolean indexing dan filtering di NumPy digunakan untuk mengambil data berdasarkan kondisi (True / False).

In [19]:
a = np.array([1,2,3,4,5,6])
print(a > 3,"\n")

modulus = a[a % 2 == 0]
print(modulus,"\n")

a[a > 4] = 0
print("Modified Array",a)

[False False False  True  True  True] 

[2 4 6] 

Modified Array [1 2 3 4 0 0]


Random number generation di NumPy digunakan untuk membuat angka acak.

seed() dipakai supaya angka random yang dihasilkan selalu sama setiap program dijalankan.

random = membuat angka acak
seed = mengunci hasil random agar konsisten/reproducible.

In [20]:

import numpy as np
random_array = np.random.rand(3,3)
print ("random array: \n ",random_array)

random_int = np.random.randint(0,10,size=(2,3))
print("random integer: \n",random_int)

np.random.seed(42)
random_seed = np.random.rand(3)
print("random seed: \n",random_seed)


random array: 
  [[0.21838321 0.59471006 0.10145277]
 [0.84451671 0.51543223 0.25178562]
 [0.98945811 0.18045365 0.0882504 ]]
random integer: 
 [[8 6 0]
 [3 5 8]]
random seed: 
 [0.37454012 0.95071431 0.73199394]


broadcasting operations

In [21]:
import numpy as np

matrix = np.array ([[1,2,3],[4,5,6],[7,8,9]])
vector = np.array([1,0,-1])

result_tambah = matrix + vector
print(result_tambah)

result_kali = matrix * vector
print(result_kali)

[[2 2 2]
 [5 5 5]
 [8 8 8]]
[[ 1  0 -3]
 [ 4  0 -6]
 [ 7  0 -9]]


filter random dataset

In [22]:
import numpy as np

dataset = np.random.randint(1,50, size =(5,5))
print("original random: \n", dataset)

dataset[dataset < 20] = 0
print("\n",dataset)

print("sum: ", np.sum(dataset))
print("mean: ", np.mean(dataset))
print("max :", np.max(dataset))
print("min :",np.min(dataset))
print("standar deviasi: ", np.std(dataset))

original random: 
 [[21 39 19 23 11]
 [11 24 36 40 24]
 [ 3 22  2 24 44]
 [30 38  2 21 33]
 [12 22 44 25 49]]

 [[21 39  0 23  0]
 [ 0 24 36 40 24]
 [ 0 22  0 24 44]
 [30 38  0 21 33]
 [ 0 22 44 25 49]]
sum:  559
mean:  22.36
max : 49
min : 0
standar deviasi:  15.944604102955958


DAY 3 PANDAS:

Series dan DataFrame
membaca file (read_csv)
filtering data
selecting column/baris
aggregation (mean, sum, dll)
handling missing values
grouping (groupby)
sorting data

In [23]:
import pandas as pd
s = pd.Series([10,20,30], index=["a","b","c"])
print(s)

data = {"Nama: ": ["sabi","fajar"], "usia: ": [23,19]}
df = pd.DataFrame(data)
print("\n",df)

print(df[["Nama: ", "usia: "]])


print(df.info())
#print(df.describe(),"\n")
#df.to_csv("data_baru.csv", index=False)
#df.to_excel("data.xlsx", index=False)

#seleksi posisi
print(df.iloc[1])
print(df.iloc[:, 0])

#seleksi label
print("lable \n", df.loc[:, "Nama: "])

a    10
b    20
c    30
dtype: int64

   Nama:   usia: 
0   sabi      23
1  fajar      19
  Nama:   usia: 
0   sabi      23
1  fajar      19
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Nama:   2 non-null      object
 1   usia:   2 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes
None
Nama:     fajar
usia:        19
Name: 1, dtype: object
0     sabi
1    fajar
Name: Nama: , dtype: object
lable 
 0     sabi
1    fajar
Name: Nama: , dtype: object


exercise

In [24]:
import pandas as pd

#load dataset
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")

print("5 pertama \n", df.head())
print("5 terakhir \n", df.tail())
print("info \n", df.info())
print("describe \n", df.describe())


5 pertama 
    sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5 terakhir 
      sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        -----------

In [27]:
selected_columns = df[["species", "sepal_length"]]
print("Selected_columns \n",selected_columns)

print("\n")

filter_rows = df[(df["sepal_length"] > 5.0) & (df["species"] == "setosa")]
print("Filtered Rows: \n", filter_rows)


Selected_columns 
        species  sepal_length
0       setosa           5.1
1       setosa           4.9
2       setosa           4.7
3       setosa           4.6
4       setosa           5.0
..         ...           ...
145  virginica           6.7
146  virginica           6.3
147  virginica           6.5
148  virginica           6.2
149  virginica           5.9

[150 rows x 2 columns]


Filtered Rows: 
     sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
10           5.4          3.7           1.5          0.2  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19   