<a href="https://colab.research.google.com/github/sabiandika/learn-code-in-google-collab/blob/main/WEEK_2%2C_DATA_SCIENCE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. NUMPY FOR NUMRICAL


In [41]:
import numpy as np

arr = np.array ([1,2,23])
print(arr,"\n")

zeros = np.zeros((2,3))
print(zeros,"\n")

ones = np.ones((2,3))
print(ones,"\n")

range_array = np.arange(1, 20, 3)
print(range_array,"\n")

linspace_arr = np.linspace(0, 9, 4)
print(linspace_arr,"\n")

random_arr = np.random.rand(2, 3)
print(random_arr,"\n")

[ 1  2 23] 

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[ 1  4  7 10 13 16 19] 

[0. 3. 6. 9.] 

[[0.36050084 0.35931084 0.60923838]
 [0.39377955 0.40907261 0.50990241]] 



In [42]:
import numpy as np

arr = np.array ([2,4,6,2,5,6])
reshaped = arr.reshape(3,2)
print(reshaped,"\n")

expanded = arr[:, np.newaxis]
print(expanded,"\n")

flattened = arr.flatten()
print(flattened,"\n")


[[2 4]
 [6 2]
 [5 6]] 

[[2]
 [4]
 [6]
 [2]
 [5]
 [6]] 

[2 4 6 2 5 6] 



MATH

In [43]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b,"\n")
print(a-b,"\n")
print(a*b,"\n")
print(a/b,"\n")

arr = np.array([4,16,25])
print(np.sqrt(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))


[5 7 9] 

[-3 -3 -3] 

[ 4 10 18] 

[0.25 0.4  0.5 ] 

[2. 4. 5.]
45
15.0
25


aray indexing slicing reshaping

In [44]:
import numpy as np

arr = np.array([1,2,3,4,5,6,56,42,23])
print(arr[2])
print(arr[-1])

print(arr[1:4])
print(arr[1:7:2])
print(arr[4:],"\n")

reshaped = arr.reshape(3,3)
print(reshaped,"\n")




3
23
[2 3 4]
[2 4 6]
[ 5  6 56 42 23] 

[[ 1  2  3]
 [ 4  5  6]
 [56 42 23]] 



In [45]:
import numpy as np
a = np.arange(1,6)
b = np.arange(6,11)

print(a)
print(b)

print("tambah",a+b)
print("kurang",a-b)
print("kali",a*b)
print("bagi",a/b)
print("pangkat",a**b)

print("\n")
print("\n")


[1 2 3 4 5]
[ 6  7  8  9 10]
tambah [ 7  9 11 13 15]
kurang [-5 -5 -5 -5 -5]
kali [ 6 14 24 36 50]
bagi [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
pangkat [      1     128    6561  262144 9765625]






In [46]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

#transpose
transpose = matrix.T
print("Transpose:\n", transpose)

another_matrix = np.array([[9,8,7],[6,5,4],[3,2,1]])
print("pertambahan:\n", matrix + another_matrix)
print("perkalian:\n", matrix * another_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
pertambahan:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
perkalian:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


DAY 2. NUMPY ADVANCED


Broadcasting di NumPy adalah fitur yang memungkinkan array dengan ukuran berbeda tetap bisa dilakukan operasi matematika tanpa harus menyamakan ukuran secara manual


Rules broadcasting di NumPy ada 3 aturan utama:

Dimensi dibandingkan dari kanan ke kiri
Shape array dicek mulai dari dimensi paling belakang.
Dua dimensi cocok jika:
ukurannya sama
contoh: (3,4) dengan (3,4)
atau salah satunya bernilai 1
contoh: (3,4) dengan (1,4)
Jika tidak sama dan tidak ada yang 1

In [47]:
import numpy as np

arr = np.array([1,2,3,5])
scalar = 2

result = arr + scalar
print(result)

matrix = np.array([[1,2,3],[4,5,6]])
scalar = 2
result = matrix + scalar
print("\n",result)

[3 4 5 7]

 [[3 4 5]
 [6 7 8]]


Aggregation di NumPy adalah proses menggabungkan banyak nilai menjadi satu nilai hasil.

Biasanya dipakai untuk:

jumlah (sum)
rata-rata (mean)
nilai terbesar (max)
nilai terkecil (min)

In [48]:

arr = np.array([[1,2,3], [4,5,6]])

print("sum",np.sum(arr))
print("mean",np.mean(arr))
print("max",np.max(arr))
print("min",np.min(arr))
print("Standar deviasi",np.std(arr))
print("Sum Baris:",np.sum(arr,axis=1))
print("Sum Kolom:",np.sum(arr,axis=0))



sum 21
mean 3.5
max 6
min 1
Standar deviasi 1.707825127659933
Sum Baris: [ 6 15]
Sum Kolom: [5 7 9]


Boolean indexing dan filtering di NumPy digunakan untuk mengambil data berdasarkan kondisi (True / False).

In [49]:
a = np.array([1,2,3,4,5,6])
print(a > 3,"\n")

modulus = a[a % 2 == 0]
print(modulus,"\n")

a[a > 4] = 0
print("Modified Array",a)

[False False False  True  True  True] 

[2 4 6] 

Modified Array [1 2 3 4 0 0]


Random number generation di NumPy digunakan untuk membuat angka acak.

seed() dipakai supaya angka random yang dihasilkan selalu sama setiap program dijalankan.

random = membuat angka acak
seed = mengunci hasil random agar konsisten/reproducible.

In [51]:

import numpy as np
random_array = np.random.rand(3,3)
print ("random array: \n ",random_array)

random_int = np.random.randint(0,10,size=(2,3))
print("random integer: \n",random_int)

np.random.seed(42)
random_seed = np.random.rand(3)
print("random seed: \n",random_seed)


random array: 
  [[0.30233257 0.14675589 0.09233859]
 [0.18626021 0.34556073 0.39676747]
 [0.53881673 0.41919451 0.6852195 ]]
random integer: 
 [[2 4 7]
 [7 9 1]]
random seed: 
 [0.37454012 0.95071431 0.73199394]


broadcasting operations

In [53]:
import numpy as np

matrix = np.array ([[1,2,3],[4,5,6],[7,8,9]])
vector = np.array([1,0,-1])

result_tambah = matrix + vector
print(result_tambah)

result_kali = matrix * vector
print(result_kali)

[[2 2 2]
 [5 5 5]
 [8 8 8]]
[[ 1  0 -3]
 [ 4  0 -6]
 [ 7  0 -9]]


filter random dataset

In [68]:
import numpy as np

dataset = np.random.randint(1,50, size =(5,5))
print("original random: \n", dataset)

dataset[dataset < 20] = 0
print("\n",dataset)

print("sum: ", np.sum(dataset))
print("mean: ", np.mean(dataset))
print("max :", np.max(dataset))
print("min :",np.min(dataset))
print("standar deviasi: ", np.std(dataset))

original random: 
 [[30 29 46  6 35]
 [41 37 24 29 49]
 [46 31 35 33 21]
 [32 23 33  3 18]
 [25 42 31  3 40]]

 [[30 29 46  0 35]
 [41 37 24 29 49]
 [46 31 35 33 21]
 [32 23 33  0  0]
 [25 42 31  0 40]]
sum:  712
mean:  28.48
max : 49
min : 0
standar deviasi:  14.27759083319031
