<a href="https://colab.research.google.com/github/sabiandika/learn-code-in-google-collab/blob/main/WEEK_2%2C_DATA_SCIENCE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. NUMPY

In [11]:
import numpy as np

arr = np.array ([1,2,23])
print(arr,"\n")

zeros = np.zeros((2,3))
print(zeros,"\n")

ones = np.ones((2,3))
print(ones,"\n")

range_array = np.arange(1, 20, 3)
print(range_array,"\n")

linspace_arr = np.linspace(0, 9, 4)
print(linspace_arr,"\n")

random_arr = np.random.rand(2, 3)
print(random_arr,"\n")

[ 1  2 23] 

[[0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]] 

[ 1  4  7 10 13 16 19] 

[0. 3. 6. 9.] 

[[0.53565525 0.61557884 0.30299097]
 [0.2494328  0.74764641 0.62376594]] 



In [16]:
import numpy as np

arr = np.array ([2,4,6,2,5,6])
reshaped = arr.reshape(3,2)
print(reshaped,"\n")

expanded = arr[:, np.newaxis]
print(expanded,"\n")

flattened = arr.flatten()
print(flattened,"\n")


[[2 4]
 [6 2]
 [5 6]] 

[[2]
 [4]
 [6]
 [2]
 [5]
 [6]] 

[2 4 6 2 5 6] 



MATH

In [19]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b,"\n")
print(a-b,"\n")
print(a*b,"\n")
print(a/b,"\n")

arr = np.array([4,16,25])
print(np.sqrt(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))


[5 7 9] 

[-3 -3 -3] 

[ 4 10 18] 

[0.25 0.4  0.5 ] 

[2. 4. 5.]
45
15.0
25


aray indexing slicing reshaping

In [29]:
import numpy as np

arr = np.array([1,2,3,4,5,6,56,42,23])
print(arr[2])
print(arr[-1])

print(arr[1:4])
print(arr[1:7:2])
print(arr[4:],"\n")

reshaped = arr.reshape(3,3)
print(reshaped,"\n")




3
23
[2 3 4]
[2 4 6]
[ 5  6 56 42 23] 

[[ 1  2  3]
 [ 4  5  6]
 [56 42 23]] 



In [32]:
import numpy as np
a = np.arange(1,6)
b = np.arange(6,11)

print(a)
print(b)

print("tambah",a+b)
print("kurang",a-b)
print("kali",a*b)
print("bagi",a/b)
print("pangkat",a**b)

print("\n")
print("\n")


[1 2 3 4 5]
[ 6  7  8  9 10]
tambah [ 7  9 11 13 15]
kurang [-5 -5 -5 -5 -5]
kali [ 6 14 24 36 50]
bagi [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
pangkat [      1     128    6561  262144 9765625]




In [40]:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

#transpose
transpose = matrix.T
print("Transpose:\n", transpose)

another_matrix = np.array([[9,8,7],[6,5,4],[3,2,1]])
print("pertambahan:\n", matrix + another_matrix)
print("perkalian:\n", matrix * another_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
pertambahan:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
perkalian:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
